packages:
  - "packages/openapi-ts-plugins/*"
  - "packages/openapi-tools"
  - "packages/openapi-recon"
  - "packages/openapi-kotlin"
  - "packages/openapi-swift"
  - "apps/*"
  - "examples/*"
  - "tooling/*"

catalog:
  "@hey-api/codegen-core": "^0.8.1"
  "@hey-api/json-schema-ref-parser": "^1.4.1"
  "@hey-api/openapi-ts": "^0.97.0"
  "@hey-api/shared": "^0.4.2"
  "@hey-api/spec-types": "^0.2.0"
  "@types/node": "^22"

patchedDependencies:
  "@ryoppippi/unplugin-typia": patches/@ryoppippi__unplugin-typia.patch
