packages:
  - "packages/openapi-ts-plugins/*"
  - "packages/openapi-tools"
  - "packages/openapi-recon"
  - "examples/*"
  - "tooling/*"

catalog:
  "@hey-api/codegen-core": "^0.8.0"
  "@hey-api/openapi-ts": "^0.96.1"
  "@hey-api/shared": "^0.4.1"
  "@types/node": "^22"

patchedDependencies:
  "@ryoppippi/unplugin-typia": patches/@ryoppippi__unplugin-typia.patch
