import type { DefinePlugin, IR, Plugin } from "@hey-api/shared";

export type TransformOperationNameFn = (
  operation: IR.OperationObject,
) => string;

export type ServerConfig = {
  /**
   * Generate server.gen.ts — the `os = implement(router)` helper used to
   * type-safely implement each procedure in your backend.
   * @default false
   */
  implementation?: boolean;
  /**
   * Scaffold handler files under `handlersDir`.
   * - New files are created with `throw new ORPCError('NOT_IMPLEMENTED')` stubs.
   * - Existing files are patched: only procedures absent from the file are appended.
   * Files are never wiped; set to `false` to disable entirely.
   * @default true when `implementation` is true
   */
  handlers?:
    | boolean
    | {
        /**
         * Directory to write handler files into.
         * Resolved relative to `process.cwd()`.
         * @default 'src/handlers'
         */
        dir?: string;
        /**
         * Path alias prefix used when importing `server.gen` inside handler files.
         * When set (e.g. `'#/'`), the import becomes `#/generated/.../server.gen`.
         * When omitted, a relative path is used instead.
         * @example '#/'
         */
        importAlias?: string;
        /**
         * Override the implementer used in generated handler stubs.
         * By default stubs import `os` from the generated `server.gen` file.
         * Use this to import a wrapper like `publicOs` from your own `procedures` module instead.
         * @example { name: 'publicOs', from: '#/procedures' }
         */
        implementer?: {
          /** The exported name to use (e.g. `'publicOs'`). */
          name: string;
          /** The module to import it from (e.g. `'#/procedures'`). */
          from: string;
        };
      };
};

export type ClientConfig = {
  /**
   * Generate an HTTP client using the native oRPC RPC protocol.
   * @default false
   */
  rpc?: boolean;
  /**
   * Generate a WebSocket client using the native oRPC RPC protocol.
   * @default false
   */
  websocket?: boolean;
  /**
   * Generate a MessagePort client (Web Workers, iframes).
   * @default false
   */
  messageport?: boolean;
  /**
   * Generate an OpenAPI-compatible REST client.
   * Use this when the server exposes standard REST endpoints.
   * @default false
   */
  openapi?: boolean;
  /**
   * Generate TanStack Query utilities (useQuery, useMutation, etc.).
   * Wraps any of the above clients.
   * @default false
   */
  tanstack?: boolean;
};

export type ClientType = keyof ClientConfig;

export type UserConfig = Plugin.Hooks &
  Plugin.UserExports & {
    name: "@ahmedrowaihi/orpc";
    /**
     * Server-side generation options.
     * Controls what backend files are produced.
     * Contracts and router are always generated regardless of this setting.
     * @example { implementation: true }
     */
    server?: ServerConfig;
    /**
     * Client-side generation options.
     * Each key enables a specific client transport or utility.
     * @example { rpc: true, tanstack: true }
     * @example { openapi: true }
     */
    client?: ClientConfig;
    /**
     * Router grouping strategy.
     * - 'tags' (default): Group by OpenAPI tags
     * - 'paths': Group by REST path structure
     * - 'flat': No grouping, all procedures at root level
     * @default 'tags'
     */
    group?: "paths" | "flat" | "tags";
    /**
     * Contract input structure mode.
     * - 'compact' (default): Flat merged schema (path + body for mutations, path + query for reads)
     * - 'detailed': Explicit { path, query, headers, body } structure
     * @default 'compact'
     */
    mode?: "detailed" | "compact";
    /**
     * Validation library to use for generated contracts.
     * - 'zod' (default): Uses Zod schemas generated by the zod plugin.
     * - 'typia': Uses Typia compile-time validators (`typia.createValidate<T>()`)
     *   referencing the TypeScript types generated by `@hey-api/typescript`.
     *   Typia v11 returns Standard Schema objects, which oRPC accepts directly.
     * @default 'zod'
     */
    validation?: "zod" | "typia";
    /**
     * Custom function to transform operation names in the router.
     * @example (operation) => operation.id.replace(/Controller_/i, '')
     */
    transformOperationName?: TransformOperationNameFn;
  };

export type Config = Plugin.Hooks &
  Plugin.Exports & {
    name: "@ahmedrowaihi/orpc";
    server: Required<Omit<ServerConfig, "handlers">> & { handlers: false | { dir: string; importAlias?: string; implementer?: { name: string; from: string } } };
    client: Required<ClientConfig>;
    group: "paths" | "flat" | "tags";
    mode: "detailed" | "compact";
    validation: "zod" | "typia";
    transformOperationName?: TransformOperationNameFn;
  };

export type ORPCPlugin = DefinePlugin<UserConfig, Config>;

// Module augmentation to register the orpc plugin in the PluginConfigMap
declare module "@hey-api/openapi-ts" {
  export interface PluginConfigMap {
    "@ahmedrowaihi/orpc": ORPCPlugin["Types"];
  }
}
