/**
 * Typia-specific contract builders.
 * Uses compile-time `typia.createValidate<T>()` referencing TypeScript types
 * generated by `@hey-api/typescript`.
 */

import { $ } from "@hey-api/openapi-ts";

import type { ORPCPlugin } from "../types";

function buildTypiaSchemaExpr(typeExpr: any, createValidateSym: any) {
  return $(createValidateSym).call().generic(typeExpr);
}

function nonNullable(typeExpr: any) {
  return $.type("NonNullable").generic(typeExpr);
}

function typeIdx(sym: any, key: string) {
  return $.type.idx($.type(sym), $.type.literal(key));
}

export function buildTypiaInput(
  plugin: ORPCPlugin["Instance"],
  operationId: string,
  mode: string,
  createValidateSym: any,
  isGetOrDelete: boolean,
  hasPathParams: boolean,
  hasQueryParams: boolean,
  bodyIsObject: boolean,
  bodyRequired: boolean,
): { expr: any; useDetailedMode: boolean } | null {
  const dataTypeSym = plugin.querySymbol({
    category: "schema",
    resource: "operation",
    resourceId: operationId,
    role: "data",
    tool: "typescript",
  });
  if (!dataTypeSym) return null;

  if (mode === "detailed") {
    const omitType = $.type("Omit")
      .generic($.type(dataTypeSym))
      .generic($.type.literal("url"));
    return {
      expr: buildTypiaSchemaExpr(omitType, createValidateSym),
      useDetailedMode: true,
    };
  }

  const typeParts: any[] = [];
  if (bodyIsObject) {
    const bodyType = typeIdx(dataTypeSym, "body");
    typeParts.push(bodyRequired ? bodyType : nonNullable(bodyType));
  }
  if (hasPathParams) typeParts.push(typeIdx(dataTypeSym, "path"));
  if (hasQueryParams && isGetOrDelete)
    typeParts.push(nonNullable(typeIdx(dataTypeSym, "query")));

  if (typeParts.length > 0) {
    const combined =
      typeParts.length === 1 ? typeParts[0] : $.type.and(...typeParts);
    return {
      expr: buildTypiaSchemaExpr(combined, createValidateSym),
      useDetailedMode: false,
    };
  }

  const omitType = $.type("Omit")
    .generic($.type(dataTypeSym))
    .generic($.type.literal("url"));
  return {
    expr: buildTypiaSchemaExpr(omitType, createValidateSym),
    useDetailedMode: true,
  };
}

export function buildTypiaOutput(
  plugin: ORPCPlugin["Instance"],
  operationId: string,
  createValidateSym: any,
): any | null {
  const responseTypeSym = plugin.querySymbol({
    category: "schema",
    resource: "operation",
    resourceId: operationId,
    role: "responses",
    tool: "typescript",
  });
  if (!responseTypeSym) return null;
  const flattenedType = $.type(responseTypeSym).idx(
    $.type(responseTypeSym).keyof(),
  );
  return buildTypiaSchemaExpr(flattenedType, createValidateSym);
}
