/**
 * A route descriptor — the minimal data needed to match an inbound request
 * against an OpenAPI operation. Designed to be tree-shakable: each route
 * generated by the codegen plugin is its own named export, so unused routes
 * disappear from the bundle.
 */
export interface Route<
  TSpec extends string = string,
  TMethod extends string = string,
> {
  /** OpenAPI path template, e.g. `/pets/{petId}` */
  spec: TSpec;
  /** URLPattern-ready pathname, e.g. `/pets/:petId` */
  pattern: string;
  /** HTTP method, lowercase. */
  method: TMethod;
  /** OperationId from the spec, when defined. */
  operationId?: string;
}
