/**
 * `Package.swift` emission.
 *
 * Two consumption modes for the generated SDK:
 *
 *  1. **Drop into an existing Xcode target.** Paste `API/` + `Models/`
 *     into your app's target sources. Everything compiles into the
 *     same module — no `import` needed inside the app, no
 *     `Package.swift`. This is the default; nothing extra is emitted.
 *
 *  2. **Standalone SwiftPM library.** Pass `package: true` (or an
 *     options object) to `generate()` and a `Package.swift` is
 *     emitted at the output root. Consumers reach for the SDK with
 *     `.package(path: "…")` (or a git URL once published) and
 *     `import <YourPackageName>`.
 *
 * Mode 2 is the right choice when the SDK is shared across multiple
 * apps, lives in its own repo, or you want a clean module boundary
 * inside a monorepo.
 */
import type { BuiltFile } from "./build.js";

export interface PackageOptions {
  /** Library / package name. Required. Becomes both the `Package(name:)`
   * and the library product name. */
  name: string;
  /** Minimum platforms. Defaults: iOS 15, macOS 13. Pass `null` for any
   * field to omit it (e.g. `{ iOS: "v16", macOS: null }`). */
  platforms?: {
    iOS?: string | null;
    macOS?: string | null;
    tvOS?: string | null;
    watchOS?: string | null;
  };
  /** Swift tools version header. Default: `5.9`. */
  toolsVersion?: string;
  /** Source dirs (relative to package root) the library target compiles.
   * Defaults to `["API", "Models"]` to match the project layout. */
  sources?: ReadonlyArray<string>;
}

const DEFAULT_PLATFORMS = {
  iOS: "v15",
  macOS: "v13",
} as const;

/**
 * Emit `Package.swift` describing a self-contained SwiftPM library
 * around the generated SDK.
 *
 * @example
 * ```swift
 * // swift-tools-version:5.9
 * import PackageDescription
 *
 * let package = Package(
 *     name: "PetstoreSDK",
 *     platforms: [.iOS(.v15), .macOS(.v13)],
 *     products: [.library(name: "PetstoreSDK", targets: ["PetstoreSDK"])],
 *     targets: [
 *         .target(
 *             name: "PetstoreSDK",
 *             path: ".",
 *             exclude: ["Package.swift"],
 *             sources: ["API", "Models"]
 *         ),
 *     ]
 * )
 * ```
 */
export function packageSwiftFile(opts: PackageOptions): BuiltFile {
  const tools = opts.toolsVersion ?? "5.9";
  const sources = opts.sources ?? ["API", "Models"];
  const platforms = renderPlatforms(opts.platforms ?? DEFAULT_PLATFORMS);

  const lines: string[] = [
    `// swift-tools-version:${tools}`,
    `// Generated by openapi-swift. Re-emitted on every codegen run.`,
    ``,
    `import PackageDescription`,
    ``,
    `let package = Package(`,
    `    name: "${opts.name}",`,
  ];
  if (platforms) {
    lines.push(`    platforms: [${platforms}],`);
  }
  lines.push(
    `    products: [`,
    `        .library(name: "${opts.name}", targets: ["${opts.name}"]),`,
    `    ],`,
    `    targets: [`,
    `        .target(`,
    `            name: "${opts.name}",`,
    `            path: ".",`,
    `            exclude: ["Package.swift"],`,
    `            sources: [${sources.map((s) => `"${s}"`).join(", ")}]`,
    `        ),`,
    `    ]`,
    `)`,
    ``,
  );

  return { path: "Package.swift", content: lines.join("\n") };
}

function renderPlatforms(p: PackageOptions["platforms"]): string {
  if (!p) return "";
  const entries: string[] = [];
  if (p.iOS) entries.push(`.iOS(.${p.iOS})`);
  if (p.macOS) entries.push(`.macOS(.${p.macOS})`);
  if (p.tvOS) entries.push(`.tvOS(.${p.tvOS})`);
  if (p.watchOS) entries.push(`.watchOS(.${p.watchOS})`);
  return entries.join(", ");
}
